general:
  buildTool: "custom"

steps:
  artifactPrepareVersion:
    enabled: false

stages:
  Build:
    npmExecuteScripts:
      runScripts: "build"

  Deploy:
    npmExecuteScripts:
      runScripts: "deploy"
